pipeline {
   agent { label 'node210' }
    
     triggers {
       // poll repo every 2 minute for changes
       pollSCM('*/1 * * * *')
  }

   stages {
     
    stage('Git') {
      steps {
        git url: 'https://github.com/jdcanas/jenkinsfile-test.git ', branch: 'test-poll'
      }
    }
    
    stage('Git2') {
        steps {
              git credentialsId: 'jenkins-ssh-github', url: 'git@github.com:DataBiosphere/leonardo.git', branch: 'jc-test-poll'
        }
    }
   }
}
